export const projects = [
  {
    id: 1,
    img: "./images/nike.png",
    title: "Nike Landing Page",
    tools: "HTML/CSS, TailwindCSS",
    github: "https://github.com/Udeme98/Tailwind-Nike",
    live: "https://udnike.netlify.app/",
  },
  {
    id: 2,
    img: "./images/shopping-cart.png",
    title: "Shopping Cart App",
    tools: "Reactjs, TailwindCSS, Redux-Toolkit, React-router",
    github: "https://github.com/Udeme98/Shopping-Cart",
    live: "https://ud-shopping-cart.netlify.app/",
  },
  {
    id: 3,
    img: "./images/expense-tracker.png",
    title: "Expense Tracker App",
    tools: "Reactjs, React-ApexChart, React-icons, TailwindCSS",
    github: "https://github.com/Udeme98/Tailwind-Nike",
    live: "https://udnike.netlify.app/",
  },
  {
    id: 4,
    img: "./images/Manage.png",
    title: "Manage Landing Page",
    tools: "HTML/CSS, TailwindCSS, JavaScript",
    github: "https://github.com/Udeme98/Manage",
    live: "https://ud-manage.netlify.app/",
  },
  {
    id: 5,
    img: "./images/advice.png",
    title: "Advice Generator App",
    tools: "Reactjs",
    github: "https://github.com/Udeme98/Advice_app",
    live: "https://udeme-advice-app.netlify.app/",
  },
  {
    id: 6,
    img: "./images/food-recipe.png",
    title: "Food Recipe App",
    tools: "Reactjs, React-router, TailwindCSS",
    github: "https://github.com/Udeme98/Food-Recipe-App",
    live: "https://udnike.netlify.app/",
  },
];
