export const projects = [
  {
    id: 1,
    img: "./images/nike.png",
    title: "Nike Landing Page",
    tools: "HTML/CSS, TailwindCSS",
    github: "https://github.com/Udeme98/Tailwind-Nike",
    live: "https://udnike.netlify.app/",
  },
  {
    id: 2,
    img: "./images/shopping-cart.png",
    title: "Shopping Cart App",
    tools: "HTML/CSS, TailwindCSS",
    github: "https://github.com/Udeme98/Tailwind-Nike",
    live: "https://udnike.netlify.app/",
  },
  {
    id: 3,
    img: "./images/expense-tracker.png",
    title: "Expense Tracker App",
    tools: "HTML/CSS, TailwindCSS",
    github: "https://github.com/Udeme98/Tailwind-Nike",
    live: "https://udnike.netlify.app/",
  },
  {
    id: 4,
    img: "./images/food-recipe.png",
    title: "Food Recipe App",
    tools: "HTML/CSS, TailwindCSS",
    github: "https://github.com/Udeme98/Tailwind-Nike",
    live: "https://udnike.netlify.app/",
  },
  {
    id: 5,
    img: "./images/qr-code.png",
    title: "QR Code Generator App",
    tools: "HTML/CSS, TailwindCSS",
    github: "https://github.com/Udeme98/Tailwind-Nike",
    live: "https://udnike.netlify.app/",
  },
  {
    id: 6,
    img: "./images/weather-app.png",
    title: "Weather App",
    tools: "HTML/CSS, TailwindCSS",
    github: "https://github.com/Udeme98/Tailwind-Nike",
    live: "https://udnike.netlify.app/",
  },
];
